/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.sql.Connection;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form pemesanan
     */
    public pemesanan() {
        initComponents();
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tagihan = new javax.swing.JLabel();
        cb02 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jam = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTiket = new javax.swing.JTextField();
        cb01 = new javax.swing.JCheckBox();
        btnPesan = new javax.swing.JButton();
        cb05 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cb03 = new javax.swing.JCheckBox();
        film = new javax.swing.JComboBox<>();
        cb06 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cb04 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new javax.swing.JTable();
        nopesan = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        btntTampil = new javax.swing.JButton();
        tagihan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tagihan.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        tagihan.setText("000");

        cb02.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb02.setText("02");
        cb02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb02ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel6.setText("Nomor Kursi");

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel1.setText("Jam");

        btnHapus.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jam.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "10.00", "13.00", "15.50", "19.00" }));

        btnEdit.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel.setText("Judul Film");

        jLabel7.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel7.setText("No. Pemesanan");

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel2.setText("Jumlah tiket");

        txtTiket.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N

        cb01.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb01.setText("01");
        cb01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb01ActionPerformed(evt);
            }
        });

        btnPesan.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        cb05.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb05.setText("05");
        cb05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb05ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel3.setText("Total");

        cb03.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb03.setText("03");
        cb03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb03ActionPerformed(evt);
            }
        });

        film.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        film.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Miracle in Cell No.7", "The Medium", "Frozen 2", "Mencuri Raden Saleh" }));
        film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmActionPerformed(evt);
            }
        });

        cb06.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb06.setText("06");
        cb06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb06ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabel4.setText("Pemesanan Tiket Film");

        cb04.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cb04.setText("04");
        cb04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb04ActionPerformed(evt);
            }
        });

        tabelPemesanan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Pemesanan", "Judul Film", "Jam", "Jumlah Tiket", "No. Kursi", "Tagihan"
            }
        ));
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);

        nopesan.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N

        btnBack1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btnBack1.setText("Kembali");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btntTampil.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        btntTampil.setText("Tampilkan Data");
        btntTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntTampilActionPerformed(evt);
            }
        });

        tagihan1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        tagihan1.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btntTampil)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBack1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnPesan)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEdit)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHapus))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addGap(36, 36, 36)
                            .addComponent(tagihan1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tagihan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb05, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb06, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb01, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb02, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb03, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb04, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel)
                                    .addComponent(jLabel7))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(film, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nopesan))))))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nopesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb02)
                            .addComponent(jLabel6)
                            .addComponent(cb01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb03)
                            .addComponent(cb04))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb05)
                            .addComponent(cb06))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tagihan)
                            .addComponent(tagihan1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesan)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack1)
                            .addComponent(btntTampil))))
                .addGap(172, 172, 172))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb02ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM pemesanan WHERE no_pemesanan =('"+nopesan.getText()+"')";
            
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.execute();
            tampilData();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
            String kursi="";
            if (cb01.isSelected())
                kursi+=cb01.getText()+" " + "\n";
            if (cb02.isSelected())
                kursi+=cb02.getText()+" " + "\n";
            if (cb03.isSelected())
                kursi+=cb03.getText()+" " + "\n";
            if (cb04.isSelected())
                kursi+=cb04.getText()+" " + "\n";
            if (cb05.isSelected())
                kursi+=cb05.getText()+" " + "\n";
            if (cb06.isSelected())
                kursi+=cb06.getText()+" " + "\n";
            
            int harga = 40000;
            int total = 0;
            int tiket = Integer.parseInt(txtTiket.getText());
            total = tiket * harga;
            
            edit();
            tampilData();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void edit(){
        String kursi="";
            if (cb01.isSelected())
                kursi+=cb01.getText()+" " + "\n";
            if (cb02.isSelected())
                kursi+=cb02.getText()+" " + "\n";
            if (cb03.isSelected())
                kursi+=cb03.getText()+" " + "\n";
            if (cb04.isSelected())
                kursi+=cb04.getText()+" " + "\n";
            if (cb05.isSelected())
                kursi+=cb05.getText()+" " + "\n";
            if (cb06.isSelected())
                kursi+=cb06.getText()+" " + "\n";
            
        int harga = 40000;
        int total = 0;
        int tiket = Integer.parseInt(txtTiket.getText());
        total = tiket * harga;
        tagihan.setText(String.valueOf(total));
        
        try{
            String sql = "UPDATE pemesanan SET judul_film='"+film.getSelectedItem()+"', jam='"+jam.getSelectedItem()+"', jumlah_tiket='"+txtTiket.getText()+"', nomor_kursi='"+kursi+"', total ='"+total+"' WHERE no_pemesanan='"+nopesan.getText()+"'";
                    
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);

            ps.execute();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    
    private void cb01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb01ActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        try {
            int harga = 40000;
            int total = 0;
            int tiket = Integer.parseInt(txtTiket.getText());
            total = tiket * harga;
            String kursi="";
            if (cb01.isSelected())
                kursi+=cb01.getText()+" " + "\n";
            if (cb02.isSelected())
                kursi+=cb02.getText()+" " + "\n";
            if (cb03.isSelected())
                kursi+=cb03.getText()+" " + "\n";
            if (cb04.isSelected())
                kursi+=cb04.getText()+" " + "\n";
            if (cb05.isSelected())
                kursi+=cb05.getText()+" " + "\n";
            if (cb06.isSelected())
                kursi+=cb06.getText()+" " + "\n";
            
            String sql = "INSERT INTO pemesanan VALUES ('"
                    + nopesan.getText()+"','"
                    + film.getSelectedItem()+"','"
                    + jam.getSelectedItem()+"','"
                    + txtTiket.getText()+"','"
                    + kursi+"','"
                    + total+"')";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.execute();
            
            tagihan.setText(String.valueOf(total));
            tampilData();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    
    private void cb05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb05ActionPerformed

    private void cb03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb03ActionPerformed

    private void filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmActionPerformed

    private void cb06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb06ActionPerformed

    private void cb04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb04ActionPerformed

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        // TODO add your handling code here:
        int i = tabelPemesanan.getSelectedRow();
        TableModel model = tabelPemesanan.getModel();
        nopesan.setText(model.getValueAt(i, 0).toString());
        String judul_film = model.getValueAt(i, 1).toString();
            switch(judul_film){
                case "Miracle in Cell No.7": 
                    film.setSelectedIndex(1);
                    break;
                case "The Medium": 
                    film.setSelectedIndex(2);
                    break;
                case "Frozen 2": 
                    film.setSelectedIndex(3);
                    break;
                case "Mencuri Raden Saleh": 
                    film.setSelectedIndex(4);
                    break;
            }
        String jam_tayang = model.getValueAt(i, 2).toString();
            switch(jam_tayang){
                case "10.00": 
                    jam.setSelectedIndex(1);
                    break;
                case "13.00": 
                    jam.setSelectedIndex(2);
                    break;
                case "15.50": 
                    jam.setSelectedIndex(3);
                    break;
                case "19.00": 
                    jam.setSelectedIndex(4);
                    break;
            }
        txtTiket.setText(model.getValueAt(i,3).toString());
        String kursi = model.getValueAt(i,4).toString();
            switch (kursi) {
            case "01 ":
                cb01.setSelected(true);
                cb02.setSelected(false);
                cb03.setSelected(false);
                cb04.setSelected(false);
                cb05.setSelected(false);
                cb06.setSelected(false);
                break;
            case "02 ":
                cb02.setSelected(true);
                cb01.setSelected(false);
                cb03.setSelected(false);
                cb04.setSelected(false);
                cb05.setSelected(false);
                cb06.setSelected(false);
                break;
            case "03 ":
                cb03.setSelected(true);
                cb01.setSelected(false);
                cb02.setSelected(false);
                cb04.setSelected(false);
                cb05.setSelected(false);
                cb06.setSelected(false);
                break;
            case "04 ":
                cb04.setSelected(true);
                cb01.setSelected(false);
                cb02.setSelected(false);
                cb03.setSelected(false);
                cb05.setSelected(false);
                cb06.setSelected(false);
                break;
            case "05 ":
                cb05.setSelected(true);
                cb01.setSelected(false);
                cb02.setSelected(false);
                cb03.setSelected(false);
                cb04.setSelected(false);
                cb06.setSelected(false);
                break;
            case "06 ":
                cb06.setSelected(true);
                cb01.setSelected(false);
                cb02.setSelected(false);
                cb03.setSelected(false);
                cb04.setSelected(false);
                cb05.setSelected(false);
                break;
            default:
                cb01.setSelected(true);
                cb02.setSelected(true);
                cb03.setSelected(true);
                cb04.setSelected(true);
                cb05.setSelected(true);
                cb06.setSelected(true);

                break;
        }


        tagihan.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void tampilData(){
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("No. Pemesanan");
        dtm.addColumn("Judul Film");
        dtm.addColumn("Jam");
        dtm.addColumn("Jumlah Tiket");
        dtm.addColumn("No. Kursi");
        dtm.addColumn("Tagihan");
        
        try{
            String sql = "SELECT * FROM pemesanan";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery(sql);
            
            ResultSetMetaData meta = rs.getMetaData();
            
            while(rs.next()){
                String nopesan = rs.getString("no_pemesanan");
                String judul_film = rs.getString("judul_film");
                String jam_tayang = rs.getString("jam");
                String txtTiket = rs.getString("jumlah_tiket");
                String nokursi = rs.getString("nomor_kursi");
                String tagihan = rs.getString("total");
                String[] data = {nopesan, judul_film, jam_tayang, txtTiket, nokursi, tagihan};
                dtm.addRow(data);
            }
            tabelPemesanan.setModel(dtm);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void btntTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntTampilActionPerformed
        tampilData();
    }//GEN-LAST:event_btntTampilActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btntTampil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb01;
    private javax.swing.JCheckBox cb02;
    private javax.swing.JCheckBox cb03;
    private javax.swing.JCheckBox cb04;
    private javax.swing.JCheckBox cb05;
    private javax.swing.JCheckBox cb06;
    private javax.swing.JComboBox<String> film;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jam;
    private javax.swing.JTextField nopesan;
    private javax.swing.JTable tabelPemesanan;
    private javax.swing.JLabel tagihan;
    private javax.swing.JLabel tagihan1;
    private javax.swing.JTextField txtTiket;
    // End of variables declaration//GEN-END:variables
}
